---
title: "adult-carryover"
author: "Erica Griffin"
date: "2026-02-18"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load( dplyr, lme4, MASS, lmerTest, here, ggplot2, DHARMa, tidyr)

adult_df <- read.csv(here("IntermediateData", "adult_carryover_df.csv"))

```

```{r}
# Create plot for differences between prev_cort and prev_carryover

ggplot(adult_df, aes(x = Individual_Treatment, y = TRF)) +  
  geom_jitter(width = 0.15, alpha = 0.6, size = 2) +
  stat_summary(fun = mean, geom = "point", size = 4, color = "pink") +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2, color = "pink") +
  theme_minimal() +
  labs(
    x = "Treatment",
    y = "Mean TRF"  )


```

```{r}
# keep only 2nd year samples for first model 
adult_df2 <- adult_df %>%
  dplyr::filter(Experiment == "Carryover")
model1 <- lm(TRF ~ Individual_Treatment, data = adult_df2)
summary(model1)
res <- simulateResiduals(model1)
plot(res)

ggplot(adult_df2, aes(x = Individual_Treatment, y = TRF)) +  
  geom_jitter(width = 0.15, alpha = 0.6, size = 2) +
  stat_summary(fun = mean, geom = "point", size = 4, color = "pink") +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2, color = "pink") +
  theme_minimal() +
  labs(
    x = "Treatment",
    y = "Mean TRF"  )
```

```{r}
# keep only 1st year samples for second model 
adult_df3 <- adult_df %>%
  dplyr::filter(Experiment == "CortDose")
model2 <- lm(TRF ~ Individual_Treatment, data = adult_df3)
summary(model2)
res <- simulateResiduals(model1)
plot(res)
```

```{r}
# model with all samples ? 
model3 <- lmer(TRF ~ Individual_Treatment + (1 | Individual_Band), data = adult_df)
summary(model2)
res <- simulateResiduals(model1)
plot(res)
```